set(CHAPTER_1_PATH test/01_arrays_strings)
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_1.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_2.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_3.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_4.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_5.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_6.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_7.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_8.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_9.cpp")

