set(CHAPTER_1_PATH test/01_arrays_strings)
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_1.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_2.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_3.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_4.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_5.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_6.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_7.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_8.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_1_PATH}/test_problem_9.cpp")

set(CHAPTER_2_PATH test/02_linked_list)
list(APPEND TEST_SOURCES "${CHAPTER_2_PATH}/test_useful.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_2_PATH}/test_problem_1.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_2_PATH}/test_problem_2.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_2_PATH}/test_problem_3.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_2_PATH}/test_problem_4.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_2_PATH}/test_problem_5.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_2_PATH}/test_problem_6.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_2_PATH}/test_problem_7.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_2_PATH}/test_problem_8.cpp")

set(CHAPTER_3_PATH test/03_stacks_queues)
list(APPEND TEST_SOURCES "${CHAPTER_3_PATH}/test_problem_1.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_3_PATH}/test_problem_2.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_3_PATH}/test_problem_3.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_3_PATH}/test_problem_4.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_3_PATH}/test_problem_5.cpp")

set(CHAPTER_4_PATH test/04_trees_graphs)
list(APPEND TEST_SOURCES "${CHAPTER_4_PATH}/test_useful.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_4_PATH}/test_problem_1.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_4_PATH}/test_problem_2.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_4_PATH}/test_problem_3.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_4_PATH}/test_problem_4.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_4_PATH}/test_problem_5.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_4_PATH}/test_problem_6.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_4_PATH}/test_problem_7.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_4_PATH}/test_problem_8.cpp")
list(APPEND TEST_SOURCES "${CHAPTER_4_PATH}/test_problem_9.cpp")
